Mission13/Models/Bowler.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class Bowler
    {
        [Key]
        [Required]
        public int BowlerID { get; set; }

        public string BowlerFirstName { get; set; }

        public string BowlerMiddleInit { get; set; }

        public string BowlerLastName { get; set; }

        public string BowlerAddress { get; set; }

        public string BowlerCity { get; set; }

        public string BowlerState { get; set; }

        public string BowlerZip { get; set; }

        public string BowlerPhoneNumber { get; set; }

        public int TeamID { get; set; }

        public Team Team { get; set; }
    }
}

Mission13/Models/BowlersDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class BowlersDbContext : DbContext
    {
        public BowlersDbContext(DbContextOptions<BowlersDbContext> options) : base(options)
        {

        }

        public DbSet<Bowler> Bowlers { get; set; }

        public DbSet<Team> Teams { get; set; }
    }
}

Mission13/Models/EFBowlingRepository.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class EFBowlingRepository : IBowlingRepository
    {
        private BowlersDbContext _context { get; set; }

        public EFBowlingRepository (BowlersDbContext temp)
        {
            _context = temp;
        }

        public IQueryable<Bowler> Bowlers => _context.Bowlers;
    }
}

Mission13/Models/IBowlingRepository.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public interface IBowlingRepository
    {
        IQueryable<Bowler> Bowlers { get; }
    }
}

Mission13/Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Mission13.Models
{
    public class Team
    {
        [Key]
        [Required]
        public int TeamID { get; set; }

        public string TeamName { get; set; }

        public int CaptainID { get; set; }
    }
}

Mission13/Components/TeamsViewComponent.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mission13.Models;

namespace Mission13.Components
{
    public class TeamsViewComponent : ViewComponent
    {
        private BowlersDbContext _context { get; set; }

        public TeamsViewComponent (BowlersDbContext temp)
        {
            _context = temp;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamName"];

            var teams = _context.Bowlers
                .Include("Team")
                .Select(x => x.Team.TeamName)
                .Distinct()
                .OrderBy(x => x);

            return View(teams);
        }
    }
}

Mission13/Controllers/HomeController.cs
 using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Mission13.Models;

namespace Mission13.Controllers
{
    public class HomeController : Controller
    {
        private BowlersDbContext _context { get; set; }

        public HomeController(BowlersDbContext temp)
        {
            _context = temp;
        }

        public IActionResult Index(string teamName)
        {
            ViewBag.SelectedTeam = RouteData?.Values["teamName"];

            var bowlers = _context.Bowlers
                .Include("Team")
                .Where(x => x.Team.TeamName == teamName || teamName == null)
                .ToList(); //join the other dataset using the .include here.

            return View(bowlers);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View("EditBowler");
        }

        [HttpPost]
        public IActionResult Add(Bowler bowler)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bowler);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Edit(int bowlerid)
        {
            var bowler = _context.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View("EditBowler", bowler); 
        }

        [HttpPost]
        public IActionResult Edit(Bowler bowler)
        {
            _context.Bowlers.Update(bowler);

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int bowlerid)
        {
            var bowler = _context.Bowlers.Single(x => x.BowlerID == bowlerid);

            return View("Delete", bowler);
        }

        [HttpPost]
        public IActionResult Delete(Bowler bowler)
        {
            var bowldelete = _context.Bowlers.Single(x => x.BowlerID == bowler.BowlerID);
            _context.Bowlers.Remove(bowldelete);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Mission13/Views/Home/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}

@model Bowler

<div class="text-center">
    <h1>Confirm Deletion</h1>


    <p>Are you sure you want to delete <b>Bowler @Model.BowlerLastName</b></p>
    <form method="post" asp-controller="Home" asp-action="Delete">
        <button type="submit">Delete</button>
        <button asp-controller="Home" asp-action="Index">Cancel</button>

        <input type="hidden" asp-for="BowlerID" />
    </form>
</div>

Mission13/Views/Home/DeleteConfirmation.cshtml
@{
    ViewData["Title"] = "DeleteConfirmation";
}

@model Bowler

<div class="text-center">
    <h1>Bowler @Model.BowlerLastName Deleted</h1>
 
</div>

Mission13/Views/Home/EditBowler.cshtml
@{
    ViewData["Title"] = "Add/Edit Bowler";
}

@model Mission13.Models.Bowler

<br />
<h2>Add/Edit Bowler</h2>
<br />

<div class="">

    <form method="post">

        <div class="form-group">
            <label asp-for="BowlerFirstName">Bowler First Name: </label>
            <input asp-for="BowlerFirstName" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerMiddleInit">Bowler Middle Initial</label>
            <input asp-for="BowlerMiddleInit" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerLastName">Bowler Last Name: </label>
            <input asp-for="BowlerLastName" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerAddress">Bowler Address: </label>
            <input asp-for="BowlerAddress" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerCity">Bowler City: </label>
            <input asp-for="BowlerCity" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerState">Bowler State: </label>
            <input asp-for="BowlerState" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerZip">Bowler Zipcode: </label>
            <input asp-for="BowlerZip" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="BowlerPhoneNumber">Bowler Phone: </label>
            <input asp-for="BowlerPhoneNumber" type="text" class="form-control" />
        </div>

        <div class="form-group">
            <label asp-for="TeamID">Bowler Team: </label>
            <select asp-for="TeamID" type="text" class="form-control">
                <option value="">Choose a team</option>
                <option value="1">Marlins</option>
                <option value="2">Sharks</option>
                <option value="3">Terrapins</option>
                <option value="4">Barracudas</option>
                <option value="5">Dolphins</option>
                <option value="6">Orcas</option>
                <option value="7">Manatees</option>
                <option value="8">Swordfish</option>
                <option value="9">Huckleberrys</option>
                <option value="10">MintJuleps</option>
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

    <br />
    <a class="btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Go Back</a>

    <div asp-validation-summary="All" style="color:red;"></div>

</div>

Mission13/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Bowler>
 
<div class="text-center">
    <br />
    <h1 class="display-4">@ViewBag.SelectedTeam Bowlers</h1>
    <p>Contact Information For The Bowlers</p>
    <br />

    <table class="table table-sm table-striped table-bordered">

        <thead class="bold">
            <tr>
                <th>First Name</th>
                <th>Middle Init</th>
                <th>Last Name</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip</th>
                <th>Phone Number</th>
                <th>Team Name</th>
                <th></th>
                <th></th>
            </tr>
        </thead>

        <tbody>

            @foreach (var b in Model)
            {
            <tr>
                <td>@b.BowlerFirstName</td>
                <td>@b.BowlerMiddleInit</td>
                <td>@b.BowlerLastName</td>
                <td>@b.BowlerAddress</td>
                <td>@b.BowlerCity</td>
                <td>@b.BowlerState</td>
                <td>@b.BowlerZip</td>
                <td>@b.BowlerPhoneNumber</td>
                <td>@b.Team.TeamName</td>
                <td><a asp-controller="Home" asp-action="Edit" asp-route-bowlerid="@b.BowlerID">Edit</a></td>
                <td><a asp-controller="Home" asp-action="Delete" asp-route-bowlerid="@b.BowlerID">Delete</a></td>
            </tr>
            }

        </tbody>

    </table>

</div>

Mission13/Views/Shared/Components/Teams/Default.cshtml
@{
}

@model IEnumerable<string>

<div class="d-grid gap-1 text-center">
    <a asp-controller="Home" asp-action="Index" asp-route-teamName="" class="btn btn-block btn-outline-secondary">Home</a>
    <br />

    <h3>Select a Team</h3>
    @foreach (string t in Model)
    {
        <a asp-controller="Home" asp-action="Index" asp-route-teamName="@t"
           class="btn-block btn @(ViewBag.SelectedTeam == t ? "btn-primary" : "btn-outline-secondary")">@t</a>
    }
</div>

Mission13/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission13</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="row">
                    <div class="col navbar-brand" style="font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif; font-size: 50px">BOWLER TOWN</div>
                    <i style="padding-top: 17px" class="fa-3x fa fa-regular fa-bowling-ball"></i>
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    <a class="nav-link text-light" asp-controller="Home" asp-action="Add">Add Bowler</a>
                </div>
                <p>Connect with other bowling fanatics!</p>
            </div>
        </div>
    </header>
    <div class="row m-1 p-1">
        <div class="col-9 container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <div id="teams" class="col-3  btn-block">
            <br />
            <vc:teams></vc:teams>
        </div>


    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Mission13
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>